POST http://localhost:3000/api/photos HTTP/1.1
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="input.jpg"
Content-Type: image/jpeg

< ./input.jpg

------FormBoundary1234
Content-Disposition: form-data; name="album"
Content-Type: text/plain

samochody
------FormBoundary1234


#############
GET http://localhost:3000/api/photos HTTP/1.1

#########

GET http://localhost:3000/api/photos/1682322052452 HTTP/1.1

#########

DELETE http://localhost:3000/api/photos/1682322084447 HTTP/1.1

##########

PATCH  http://localhost:3000/api/photos HTTP/1.1
content-type: application/json

{
  "id": 1681642379966,
  "a": 111111
}

############

GET http://localhost:3000/api/tags/raw

###############

GET http://localhost:3000/api/tags

############

GET http://localhost:3000/api/tags/1

#############

POST http://localhost:3000/api/tags

{
  "name": "newTag1236",
  "popularity": 10000
}

######

PATCH http://localhost:3000/api/photos/tags

{
  "id": 1681642937166,
  "tag":{
    
  "name": "newTag123126",
  "popularity": 10000

  }
}

##########

PATCH http://localhost:3000/api/photos/tags/mass

{
  "id": 1682077503471,
  "tags":[{
    "name": "newTag123126",
  "popularity": 10000
  },    {
               "name": "#nowytagdlazdjęcia1",
               "popularity": 1
          },
          {
               "name": "#nowytagdlazdjęcia2",
               "popularity": 2
          },
          {
               "name": "#nowytagdlazdjęcia3",
               "popularity": 3
          }]
}


#######

GET http://localhost:3000/api/photos/tags/1681643418823
#####


GET http://localhost:3000/api/filters/metadata/1681719519975


#####
PATCH http://localhost:3000/api/filters

{
  "id": 1684003203513,
  "url":"/Users/jakub/Desktop/InstaApp/server/uploads/samochody/upload_1684003203512.jpg",
  "type": "tint",
  "params": {"r": 255, "g":0, "b":0}
}

####

GET http://localhost:3000/api/getfile/1684003203513/tint

####

POST http://localhost:3000/api/user/register

{
  "name": "Jakub",
  "lastName": "Ryszka",
  "email": "adskjhfgkjh@jkdsfkl.pl",
  "password": "dskajgfaklsjhgf,jha34532"
}