POST http://localhost:3000/api/photos HTTP/1.1
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="input.jpg"
Content-Type: image/jpeg

< ./input.jpg

------FormBoundary1234
Content-Disposition: form-data; name="album"
Content-Type: text/plain

samochody
------FormBoundary1234


#############
GET http://localhost:3000/api/photos HTTP/1.1

#########

GET http://localhost:3000/api/photos/1681200839758 HTTP/1.1

#########

DELETE http://localhost:3000/api/photos/1681200839758 HTTP/1.1

##########

PATCH  http://localhost:3000/api/photos HTTP/1.1
content-type: application/json

{
  "id": 1681200869492,
  "a": 111111
}

############

GET http://localhost:3000/api/tags/raw

###############

GET http://localhost:3000/api/tags

############

GET http://localhost:3000/api/tags/1